Relase0.1
evabase/evabase-subgraph pull request #2
Opened 2022-06-09 06:54 UTC by jadynjiang

2022-06-09 08:20 UTC, ysqi requested changes
1. 代码中有讨论过如何寻找Flow和Order ID之间关系的逻辑并没有根据会议实现。逻辑结构依旧是早期版本。

2. 请了解The Graph的 --network 参数和 network-file 参数的用法，以便在一个分支中管理不同网络，不同环境下的合约，合约地址更新问题。

3. 请解决Review提出的一些意见。

2022-06-09 08:20 UTC, ysqi commented on schema.graphql
> +  blockTIme: BigInt!
大小写 blockTime

2022-06-09 08:20 UTC, ysqi commented on src/helpers.ts
> +export const EVAFLOW_CONTROLLER_ADDRESS = '0x7eA10f2840c8B6E734697D998043653C25139C47'
所有合约地址均需要配置在 networks.json 文件中，根据不同运行环境加载。否则通过不同Git仓库分支来维护代码对于后期非常不方便。

2022-06-09 08:20 UTC, ysqi commented on src/helpers.ts
> +export function getFlowStatus(flowId: string): string {
理论上Flow的状态不需要从合约中再次读起，而是根据事件来更新维护状态。

2022-06-09 08:20 UTC, ysqi commented on src/helpers.ts
> +        flowHistory.content = 'nft order create'
‘nft order create’ 修改成 ‘create NFT order’

2022-06-09 08:20 UTC, ysqi commented on src/helpers.ts
> +        flowHistory.content = 'erc20 order create'
'erc20 order create' 修改成 'create ERC20 Limit order'

2022-06-09 08:20 UTC, ysqi commented on src/helpers.ts
> +        flowHistory.content = 'task create'
'task create' 修改成 'create custom task'

2022-06-09 08:20 UTC, ysqi commented on src/helpers.ts
> +          flowHistory.content = 'buy NFT item'
`buy NFT item` 简写成 `buy`

2022-06-09 08:20 UTC, ysqi commented on src/helpers.ts
> +          flowHistory.content = 'buy token'
`buy token` 简写成 `buy` 因为在该Flow中已经明确说明是 ERC20 Limit Order

2022-06-09 08:20 UTC, ysqi commented on src/helpers.ts
> +          flowHistory.content = 'do task'
`do task` 修改成 `execute`

2022-06-09 08:20 UTC, ysqi commented on src/helpers.ts
> +        flowHistory.content = 'flow close'
`flow close` 修改成 `close` , Flow 这个概念我们并没有传递给用户，用户只知道是 Task 或者 Create Order，这里我们统一为 close

2022-06-09 08:20 UTC, ysqi commented on src/helpers.ts
> +export let CREATE_ACTION = '1'
Action 应该定义成一组枚举，这样能方便前端服用，也能合并Execute的两种情况。

```ts
enum FlowAction {
   Unkown, Create, Upgrade, ExecuteSuccessed, ExecuteFailed、Close

}
```

2022-06-09 08:20 UTC, ysqi commented on src/mapping.ts
> +    let contract = EvaFlowController.bind(Address.fromString(EVAFLOW_CONTROLLER_ADDRESS))
绑定时，不要使用固定的合约地址，而是之间取 `event.from` 地址，等同于 Controller 合约地址。其他地方也有相同问题。

2022-06-09 08:20 UTC, ysqi commented on src/mapping.ts
> +        let lobContract = LOBExchange.bind(Address.fromString(LOB_EXCHANGE_ADDRESS))
存储  ERC20Order 信息不应该在 FlowCreate  事件中处理，应该是在 LOB的 OrderCreated  事件中进行处理。
当前的代码处理方式并没有按照会议沟通的方式处理。在Flow中只需要更新下Flow和Order的关系。

2022-06-09 08:20 UTC, ysqi commented on src/mapping.ts
> +    saveFlowHistory(flowHistory, entity, event, ZERO_BI, CREATE_ACTION, ZERO_BI, ZERO_BI, flowId, createHash, true)
flowHistory ID = createHash + index.toString() ，修改成 ID= `${createHash}#${index}` 一是优化代码，二是在多增加一个连接符`#`，其他数据的ID也采用这种方案。

2022-06-09 08:20 UTC, ysqi commented on src/mapping.ts
> +        let result = contract.getFlowMetas(BigInt.fromString(flowId))
都已经有 Flow Closed 事件，Flow必然已经是 Closed，无需再读区合约数据进行状态处理。

2022-06-09 08:20 UTC, ysqi commented on src/mapping.ts
> +        let newdetails = entity.details
这段代码可以优化成

```ts
entity.details= entity.details? [flowHistory.id]:entity.details.push(flowHistory.id)
```

但这里有一个非常大的风险点在于每次更新entiry都在重新更新一次  entity.details ，这不能保证 The Graph是否会花费大量存储费。

2022-06-09 08:20 UTC, ysqi commented on src/helpers.ts
> +export let ACTIVE = 'Active'
请将 Flow Status 也定义为枚举。

2022-06-09 08:20 UTC, ysqi commented on src/mapping.ts
> +        entity.flowStatus = getFlowStatus(flowId)
这里是Flow的执行事件，不应该处理 flowStatus。因为FlowStatus 只需要在FlowCreated和Flow Closed事件中处理。

2022-06-09 08:20 UTC, ysqi commented on src/mapping.ts
> +        if (gasFee) {
这里的 gasFees 不会是一个空置，默认是是0。所以直接简写成 `entity.gasFees=entity.gasFees!.push(event.params.payAmountByETH)`。
同样包括 handleFlowExecuteSuccess 事件中的处理。因为这两个事件的逻辑差别非常小，应该合并这两个事件的逻辑处理。

2022-06-09 08:20 UTC, ysqi commented on src/mapping.ts
> +export function handleFlowUpdated(event: FlowUpdated): void { }
删除这行无效代码

2022-06-09 08:20 UTC, ysqi commented on src/nftmapping.ts
> +    entity.admin = event.params.user.toHexString()
这里的一部分对于 FlowEntiry 的处理代码和 Flow Created 事件中相同。应该在这里移除重复的部分。

2022-06-09 08:20 UTC, ysqi commented on src/opsmapping.ts
> +    entity.admin = event.params.user.toHexString()
同样有重复处理的代码

2022-06-09 08:20 UTC, ysqi commented on subgraph.yaml
> +      eventHandlers:
请移除所有并不处理的事件，因为这将影响The Graph质押。

2022-06-14 15:21 UTC, jadynjiang commented on src/mapping.ts
> +export function handleFlowUpdated(event: FlowUpdated): void { }
the graph必须在mapping中 增加所有的 event 事件， 即时是不处理

2022-06-20 16:55 UTC, merged

2022-06-21 03:00 UTC, ysqi commented on src/helpers.ts
> +export const EVAFLOW_CONTROLLER_ADDRESS = '0x7eA10f2840c8B6E734697D998043653C25139C47'
该问题暂缓，理论上是可行的。

2022-06-22 07:07 UTC, ysqi commented on src/mapping.ts
> +        let newdetails = entity.details
```ts
entity.details!.push(flowHistory.id) 
```